image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest

.BSP-3.0.0-update2:kirkstone:
  stage: build
  tags:
    - yocto
  variables:
    GIT_STRATEGY: none
    POKY_REV: 453be4d258f71855205f45599eea04589eb4a369
    OPENEMBEDDED_REV: 166ef8dbb14ad98b2094a77fcf352f6c63d5abf2
    GPLV2_REV: d2f8b5cdb285b72a4ed93450f6703ca27aa42e8a
    VIRTUALIZATION_REV: 2fae71cdf0e8c6f398f51219bdf31eac76c662ec
    EWAOL_REV: 26b2d08f70dcc0e046da8544c968064773c7cc45
    ARM_REV: fc09cc0e8db287600625e64905170a6de24f2686
    CONF_DIR: meta-renesas/docs/template/conf/${PLATFORM}
    DL_DIR: ${CI_PROJECT_DIR}/downloads
    SSTATE_DIR: ${CI_PROJECT_DIR}/sstate_cache
  before_script:
    - export
    - rm -rf build && sync
    - mkdir build && cd build
    - git clone https://git.yoctoproject.org/git/poky
    - cd poky && git checkout ${POKY_REV} && cd -
    - git clone https://git.openembedded.org/meta-openembedded
    - cd meta-openembedded && git checkout ${OPENEMBEDDED_REV}  && cd -
    - cd meta-openembedded && git cherry-pick 3a76ff41a 16f08eb5a && cd -
    - git clone https://git.yoctoproject.org/git/meta-gplv2
    - cd meta-gplv2 && git checkout ${GPLV2_REV} && cd -
    - git clone https://git.yoctoproject.org/git/meta-virtualization
    - cd meta-virtualization && git checkout ${VIRTUALIZATION_REV} && cd -
    - git clone https://git.gitlab.arm.com/ewaol/meta-ewaol.git
    - cd meta-ewaol && git checkout ${EWAOL_REV} && cd -
    - git clone https://git.yoctoproject.org/git/meta-arm
    - cd meta-arm && git checkout ${ARM_REV} && cd -
    - git clone git@gitlab.renesas.solutions:spl2/civil-infrastructure-platform/meta-renesas.git
    - cd meta-renesas && git checkout ${CI_COMMIT_REF_NAME} && cd -
    - source poky/oe-init-build-env
    - cp ${CI_PROJECT_DIR}/build/${CONF_DIR}/*.conf conf/
    - if [ -z "${NO_CACHE+x}" ]; then echo "DL_DIR=\"${DL_DIR}\"" >> conf/local.conf; fi
    - if [ -z "${NO_CACHE+x}" ]; then echo "SSTATE_DIR=\"${SSTATE_DIR}\"" >> conf/local.conf; fi
  cache:
    - key: "downloads"
      paths:
        - ${DL_DIR}
    - key: "sstate-cache-${PLATFORM}-${IMAGE}"
      paths:
        - ${SSTATE_DIR}
  artifacts:
    expire_in: 1 week
    paths:
      - build/build/conf/
      - build/build/tmp/deploy/images/
      - build/build/tmp/deploy/licenses/
    when: always

.ewaol-base:
  extends: .BSP-3.0.0-update2:kirkstone
  script:
    - bitbake-layers add-layer ../meta-ewaol/meta-ewaol-distro
    - echo "DISTRO=\"ewaol\"" >> conf/local.conf
    - echo "DISTRO_FEATURES:append=\" ewaol-baremetal\"" >> conf/local.conf
    - echo "INCOMPATIBLE_LICENSE:remove=\"GPL-3.0-only GPL-3.0-or-later\"" >> conf/local.conf
    - echo "MACHINE_FEATURES:append=\" docker\"" >> conf/local.conf
    - echo "CONTAINERS_CONFIG_FILE_MD5=\"a371e6a60c50f1e2b80806e0601090d6\"" >> conf/local.conf

.ewaol-test:
  extends: .ewaol-base
  script:
    - !reference [.ewaol-base, script]
    - bitbake-layers add-layer ../meta-ewaol/meta-ewaol-tests
    - bitbake-layers add-layer ../meta-arm/meta-arm-toolchain
    - bitbake-layers add-layer ../meta-arm/meta-arm
    - echo "DISTRO_FEATURES:append=\" ewaol-test\"" >> conf/local.conf

.ewaol-sdk:
  extends: .ewaol-base
  script:
    - !reference [.ewaol-base, script]
    - bitbake-layers add-layer ../meta-arm/meta-arm-toolchain
    - bitbake-layers add-layer ../meta-arm/meta-arm
    - echo "DISTRO_FEATURES:append=\" ewaol-sdk\"" >> conf/local.conf

ewaol-baremetal-image:
  extends: .ewaol-base
  variables:
    IMAGE: ewaol-baremetal-image
  script:
    - !reference [.ewaol-base, script]
    - bitbake ${IMAGE}
  parallel:
    matrix:
      - PLATFORM:
          - hihope-rzg2m
          - smarc-rzg2l

ewaol-baremetal-image:validation:
  extends: .ewaol-test
  variables:
    IMAGE: ewaol-baremetal-image
  script:
    - !reference [.ewaol-test, script]
    - bitbake ${IMAGE}
  parallel:
    matrix:
      - PLATFORM:
          - hihope-rzg2m
          - smarc-rzg2l

ewaol-baremetal-image:all:
  extends: .ewaol-base
  variables:
    IMAGE: ewaol-baremetal-image
  script:
    - !reference [.ewaol-base, script]
    - bitbake ${IMAGE}
  parallel:
    matrix:
      - PLATFORM:
          - hihope-rzg2h
          - hihope-rzg2n
          - ek874
          - smarc-rzg2lc
          - smarc-rzg2ul
  when: manual

ewaol-baremetal-image:validation:all:
  extends: .ewaol-test
  variables:
    IMAGE: ewaol-baremetal-image
  script:
    - !reference [.ewaol-test, script]
    - bitbake ${IMAGE}
  parallel:
    matrix:
      - PLATFORM:
          - hihope-rzg2h
          - hihope-rzg2n
          - ek874
          - smarc-rzg2lc
          - smarc-rzg2ul
  when: manual

ewaol-baremetal-image:sdk:
  extends: .ewaol-sdk
  variables:
    IMAGE: ewaol-baremetal-sdk-image
  script:
    - !reference [.ewaol-sdk, script]
    - bitbake ${IMAGE}
  parallel:
    matrix:
      - PLATFORM:
          - hihope-rzg2m
          - smarc-rzg2l

ewaol-baremetal-image:sdk:all:
  extends: .ewaol-sdk
  variables:
    IMAGE: ewaol-baremetal-sdk-image
  script:
    - !reference [.ewaol-sdk, script]
    - bitbake ${IMAGE}
  parallel:
    matrix:
      - PLATFORM:
          - hihope-rzg2h
          - hihope-rzg2n
          - ek874
          - smarc-rzg2lc
          - smarc-rzg2ul
  when: manual

BSP-3.0.0-update2:kirkstone:
  extends: .BSP-3.0.0-update2:kirkstone
  variables:
    IMAGE: core-image-minimal
  script:
    - bitbake ${IMAGE}
  parallel:
    matrix:
      - PLATFORM:
          - hihope-rzg2h
          - hihope-rzg2m
          - hihope-rzg2n
          - ek874
          - smarc-rzg2l
          - smarc-rzg2lc
          - smarc-rzg2ul
  when: manual
